data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

custom_reward_function:
  path: null
  name: compute_score

ray_init:
  num_cpus: null # `None` は全CPUを使用することを意味しますが、SLURMなどの制限されたシステムではハングする可能性があります。許可された数値を設定してください。
  timeline_json_file: null
