options:

  save_path: ./profiler_data

  roles: ["all"]

  level: level1

  with_memory: False

  record_shapes: False

  with_npu: True

  with_cpu: True

  with_module: False

  with_stack: False

  analysis: True
