defaults:

  - ref

  - _self_

fsdp_config:

  _target_: verl.workers.config.FSDPEngineConfig

  wrap_policy:

    min_num_params: 0

  param_offload: False

  reshard_after_forward: True

  forward_prefetch: False

ulysses_sequence_parallel_size: ${oc.select:actor_rollout_ref.actor.ulysses_sequence_parallel_size,1}

entropy_from_logits_with_chunking: False

entropy_checkpointing: False
