# actor_rollout_ref.ref: actor と同じ FSDP 設定。7B より大きなモデルの場合、デフォルトで ref のオフロードを有効にすることを推奨lt
strategy: ${actor_rollout_ref.actor.strategy}

# actor_rollout_ref.actor.use_torch_compile が存在する場合はその値、そうでなければ 1
use_torch_compile: ${oc.select:actor_rollout_ref.actor.use_torch_compile,true}

log_prob_micro_batch_size: null

log_prob_micro_batch_size_per_gpu: null

# actor_rollout_ref.actor.use_dynamic_bsz が存在する場合はその値、そうでなければ false
log_prob_use_dynamic_bsz: ${oc.select:actor_rollout_ref.actor.use_dynamic_bsz,false}

# actor_rollout_ref.actor.ppo_max_token_len_per_gpu が存在する場合はその値、そうでなければ 16384
log_prob_max_token_len_per_gpu: ${oc.select:actor_rollout_ref.actor.ppo_max_token_len_per_gpu,16384}
